### ISSUE TITLE
Print image titles with `u''`

### ISSUE THREAD

**Issue by almereyda** [Flimm/backup-all-my-flickr-photos#3]
The images download nicely, but in every line the client tells me they are entitled `u''`.

**Comment by Flimm** [comment]
That's the empty Unicode string in Python 2. It means the images have no title. Is that correct, do your photos have no title?

**Comment by almereyda** [comment]
Yes, I was shooting a bit quick. Further images would have complete u'Title
of Image' strings printed.

**Comment by Flimm** [comment]
OK, I've changed the title to reflect that we don't want the confusing `u''` syntax.

**Comment by hombit** [comment]
Done in e779ad1
