### ISSUE TITLE
Let's port this to Python 3

### ISSUE THREAD

**Issue by Flimm** [Flimm/backup-all-my-flickr-photos#4]
Since this isn't a dependency for other projects, we're free to make this Python 3 only.

**Comment by hombit** [comment]
The only problem is `flickr_api` module:
```
>>> import flickr_api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/flickr_api/__init__.py", line 28
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by Flimm** [comment]
I've posted this issue on `flickr_api`, asking whether a port would be accepted, but so far no response: https://github.com/alexis-mignon/python-flickr-api/issues/75

It might be easier to find a way to go without this library.

**Comment by hombit** [comment]
I think that the [Licence](https://github.com/alexis-mignon/python-flickr-api/blob/master/LICENSE.txt) allows us to make a fork.

**Comment by hombit** [comment]
I've started to port `flickr_api` to Python 3: https://github.com/hombit/python-flickr-api
I need to test it before PR to the main repo. I think if a PR wouldn't accepted for a some reasonable period, I can create a fork of `flickr_api` with the different name and put it on PyPi.

**Comment by hombit** [comment]
I've made PR to `flickr_api` repo: https://github.com/alexis-mignon/python-flickr-api/pull/76

**Comment by Flimm** [comment]
@hombit, you're a legend. I hope it gets merged.

**Comment by Flimm** [comment]
It got merged! `flickr_api` hasn't yet been released to Pypi, but I'm going to start playing with it.

**Comment by Flimm** [comment]
The new version of `flickr_api` that supports Python 3 has been released on Pypi!

**Comment by Flimm** [comment]
The new release v0.7 includes support for Python 3. https://pypi.org/project/backup_all_my_flickr_photos/
