### ISSUE TITLE
README info

### ISSUE THREAD

**Issue by emijrp** [Flimm/backup-all-my-flickr-photos#7]
Please, indicate in README if this script downloads metadata (title, description, tags, etc) and which schema it uses for filenames (ID, title, etc).

**Comment by Flimm** [comment]
It does not download metadata in a separate location, but it does use some metadata to create the filenames. I'll look at improving the README.md file.

**Comment by Flimm** [comment]
Fixed by 461c08617e158d74061a748f7cc36d801b8d7396
